# -*- coding: utf-8 -*-
"""Python_Assignment.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxJlxgNphjBrhEg2A9p0SJJK4s8sqjjv
"""

print("Ankita Saha")

num1=int(input("Enter 1st number\n"))
num2=int(input("Enter 2nd number\n"))
avg=(num1+num2)//2
print("Aggregate=:",avg)

print("Area of circle is",3.14*2*2)

rad=float(input())
print("Area of circle is",3.14*rad**2)

num1=int(input("Enter 1st number\n"))
num2=int(input("Enter 2nd number\n"))
sum=(num1+num2)
print("Sum=",sum)

principal=float(input("Enter principal amount:"))
duration=float(input("Enter duration of loan:"))
rate=float(input("Enter rate of interest:"))
print("Total Interest=",(int)((principal*duration*rate)/100))

fahrenheit = float(input("Enter temperature in fahrenheit"))
celsius = (fahrenheit - 32) / 1.8
print("Temperature=",celsius)

C,D=int( input("Enter a two value: ").split())
print("The values of C and D are",C+D-C,C+D-D)

rev=0
num=int(input("Enter a two digit number:"))
while(num>0):
  r=num%10
  rev=rev*10+r
  num=num//10
print("Reverse of the given number is:",rev)

